// <auto-generated />
using System;
using COService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COService.Infrastructure.Migrations
{
    [DbContext(typeof(COServiceDbContext))]
    [Migration("20260730163623_RefactorCodesNiuEtat")]
    partial class RefactorCodesNiuEtat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("COService.Domain.Entities.Abonnement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Exportateur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("exportateur");

                    b.Property<string>("FactureNo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("factureNo");

                    b.Property<string>("Formule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("formule");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Numero")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("numero");

                    b.Property<string>("Partenaire")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("partenaire");

                    b.Property<string>("Statut")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Statut");

                    b.Property<string>("TypeCO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("type_co");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId")
                        .IsUnique()
                        .HasFilter("[certificate_id] IS NOT NULL");

                    b.ToTable("Abonnements", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Aeroport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.Property<Guid?>("PaysId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PaysId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Aeroports_Code");

                    b.HasIndex("PaysId");

                    b.ToTable("Aeroports", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.BattantPavillon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Designation");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_BattantsPavillon_Code");

                    b.ToTable("BattantsPavillon", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.BureauDedouanement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_BureauxDedouanements_Code");

                    b.ToTable("BureauxDedouanements", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CarnetAdresse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Adresse")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Adresse");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<string>("Coordonnees")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Coordonnees");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.Property<string>("RaisonSociale")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RaisonSociale");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CarnetsAdresses_Code");

                    b.HasIndex("Nom")
                        .HasDatabaseName("IX_CarnetsAdresses_Nom");

                    b.ToTable("CarnetsAdresses", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CategorieTarifaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("DivisionCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("DivisionCode");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DivisionId");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_CategoriesTariffaires_Code");

                    b.HasIndex("DivisionId");

                    b.ToTable("CategoriesTariffaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatLigne", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificatId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CertificatId");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Devise")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Devise");

                    b.Property<string>("DeviseCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DeviseCode");

                    b.Property<string>("HSCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HSCode");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("NatureProduit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("NatureProduit");

                    b.Property<string>("PoidsBrut")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PoidsBrut");

                    b.Property<string>("PoidsNet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PoidsNet");

                    b.Property<string>("PositionTarifaire")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PositionTarifaire");

                    b.Property<string>("ProduitCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ProduitCode");

                    b.Property<string>("Quantite")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Quantite");

                    b.Property<string>("UniteStatistique")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UniteStatistique");

                    b.Property<string>("UniteStatistiqueCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UniteStatistiqueCode");

                    b.Property<string>("ValeurFOB")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ValeurFOB");

                    b.Property<string>("Volume")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Volume");

                    b.HasKey("Id");

                    b.HasIndex("CertificatId");

                    b.HasIndex("ProduitCode");

                    b.ToTable("CertificatLignes", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatOrigine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AbonnementId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("abonnement_id");

                    b.Property<string>("AeroportCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("AeroportCode");

                    b.Property<string>("BattantPavillonCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BattantPavillonCode");

                    b.Property<string>("BureauDedouanementCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("BureauDedouanementCode");

                    b.Property<string>("CarnetAdresseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CarnetAdresseCode");

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CertificateNo");

                    b.Property<string>("CodeDocument")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CodeDocument");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("DeviseCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("DeviseCode");

                    b.Property<string>("EtatCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EtatCode");

                    b.Property<string>("ExportateurNIU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ExportateurNIU");

                    b.Property<string>("ExportateurNom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ExportateurNom");

                    b.Property<string>("Formule")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Formule");

                    b.Property<string>("MandataireNIU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MandataireNIU");

                    b.Property<string>("MandataireNom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MandataireNom");

                    b.Property<string>("ModePaiement")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("ModePaiement");

                    b.Property<string>("ModePaiementCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ModePaiementCode");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("ModuleCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("ModuleCode");

                    b.Property<string>("Navire")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("navire");

                    b.Property<string>("Observation")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Observation");

                    b.Property<string>("PartenaireNIU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PartenaireNIU");

                    b.Property<string>("PartenaireNom")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("PartenaireNom");

                    b.Property<string>("PaysDestinationCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("PaysDestinationCode");

                    b.Property<string>("PortCongoCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PortCongoCode");

                    b.Property<string>("PortSortieCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("PortSortieCode");

                    b.Property<string>("RouteCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RouteCode");

                    b.Property<Guid?>("TypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TypeId");

                    b.Property<string>("ZoneProductionCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ZoneProductionCode");

                    b.HasKey("Id");

                    b.HasIndex("AbonnementId");

                    b.HasIndex("AeroportCode");

                    b.HasIndex("BattantPavillonCode");

                    b.HasIndex("BureauDedouanementCode");

                    b.HasIndex("CarnetAdresseCode");

                    b.HasIndex("CertificateNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Certificats_CertificateNo");

                    b.HasIndex("DeviseCode");

                    b.HasIndex("EtatCode");

                    b.HasIndex("ModuleCode");

                    b.HasIndex("PaysDestinationCode");

                    b.HasIndex("PortCongoCode");

                    b.HasIndex("PortSortieCode");

                    b.HasIndex("RouteCode");

                    b.HasIndex("TypeId");

                    b.HasIndex("ZoneProductionCode");

                    b.ToTable("Certificats", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("designation");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_TypesCertificats_code");

                    b.ToTable("TypesCertificats", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateValidation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<string>("Commentaire")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Commentaire");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Etape")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Etape");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("RoleVisa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("RoleVisa");

                    b.Property<string>("VisaPar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("VisaPar");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("ValidationsCertificats", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.ChapitreTarifaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<Guid?>("SectionTarifaireId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SectionTarifaireId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ChapitresTariffaires_Code");

                    b.HasIndex("SectionTarifaireId");

                    b.ToTable("ChapitresTariffaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Commentaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CertificateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("certificate_id");

                    b.Property<string>("CommentaireText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Commentaire");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("CertificateId");

                    b.ToTable("Commentaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Corridor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Corridors_Code");

                    b.ToTable("Corridors", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Departement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Departements_Code");

                    b.ToTable("Departements", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Devise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.Property<string>("Symbole")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Symbole");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Devises_Code");

                    b.ToTable("Devises", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.DivisionTarifaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<Guid?>("ChapitreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ChapitreId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("ChapitreId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_DivisionsTariffaires_Code");

                    b.ToTable("DivisionsTariffaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Etat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<string>("CodeEcran")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CodeEcran");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Libelle");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Etats_Code");

                    b.ToTable("Etats", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Incoterm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ModuleId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Incoterms_Code");

                    b.HasIndex("ModuleId");

                    b.ToTable("Incoterms", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Modules_Code");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Pays", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Pays_Code");

                    b.ToTable("Pays", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Port", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.Property<Guid?>("PaysId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PaysId");

                    b.Property<string>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Ports_Code");

                    b.HasIndex("PaysId");

                    b.ToTable("Ports", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.PositionTarifaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<Guid?>("CategorieCodeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CategorieCodeId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("CategorieCodeId");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_PositionsTariffaires_Code");

                    b.ToTable("PositionsTariffaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Produit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Categorie")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Categorie");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.Property<string>("UniteStatistique")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UniteStatistique");

                    b.Property<string>("UniteStatistiqueCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UniteStatistiqueCode");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Produits_Code");

                    b.ToTable("Produits", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.RouteNationale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_RoutesNationales_Code");

                    b.ToTable("RoutesNationales", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Section", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Sections_Code");

                    b.ToTable("Sections", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.SectionTarifaire", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_SectionsTariffaires_Code");

                    b.ToTable("SectionsTariffaires", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.TauxDeChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<Guid>("DeviseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeviseId");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Source");

                    b.Property<decimal>("Taux")
                        .HasColumnType("decimal(20, 5)")
                        .HasColumnName("Taux");

                    b.Property<string>("ValideDe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ValideDe");

                    b.HasKey("Id");

                    b.HasIndex("DeviseId");

                    b.ToTable("TauxDeChanges", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Troncon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<Guid?>("CorridorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CorridorId");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<Guid?>("RouteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RouteId");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Troncons_Code");

                    b.HasIndex("CorridorId");

                    b.HasIndex("RouteId");

                    b.ToTable("Troncons", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.UniteStatistique", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Actif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("Actif");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_UniteStatistiques_Code");

                    b.ToTable("UniteStatistiques", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.ZoneProduction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<DateTime?>("CreeLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreeLe");

                    b.Property<string>("CreePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CreePar");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<string>("ModifiePar")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ModifiePar");

                    b.Property<DateTime?>("ModifierLe")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("ModifierLe");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Nom");

                    b.Property<string>("PartenaireNIU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PartenaireNIU");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ZonesProductions_Code");

                    b.ToTable("ZonesProductions", (string)null);
                });

            modelBuilder.Entity("COService.Infrastructure.Sagas.CertificatPostValidationState", b =>
                {
                    b.Property<Guid>("CorrelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CertificateNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExportateurNIU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FacturationRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NumeroFacture")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PartenaireNIU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PdfRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.HasKey("CorrelationId");

                    b.ToTable("SagasCertificatPostValidation", (string)null);
                });

            modelBuilder.Entity("COService.Domain.Entities.Abonnement", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "Certificate")
                        .WithOne()
                        .HasForeignKey("COService.Domain.Entities.Abonnement", "CertificateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("COService.Domain.Entities.Aeroport", b =>
                {
                    b.HasOne("COService.Domain.Entities.Pays", "Pays")
                        .WithMany("Aeroports")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("COService.Domain.Entities.CategorieTarifaire", b =>
                {
                    b.HasOne("COService.Domain.Entities.DivisionTarifaire", "Division")
                        .WithMany("CategoriesTariffaires")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Division");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatLigne", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "CertificatOrigine")
                        .WithMany("CertificatLignes")
                        .HasForeignKey("CertificatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COService.Domain.Entities.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CertificatOrigine");

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatOrigine", b =>
                {
                    b.HasOne("COService.Domain.Entities.Abonnement", "Abonnement")
                        .WithMany("Certificats")
                        .HasForeignKey("AbonnementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COService.Domain.Entities.Aeroport", "Aeroport")
                        .WithMany()
                        .HasForeignKey("AeroportCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.BattantPavillon", "BattantPavillon")
                        .WithMany("Certificats")
                        .HasForeignKey("BattantPavillonCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.BureauDedouanement", "BureauDedouanement")
                        .WithMany()
                        .HasForeignKey("BureauDedouanementCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.CarnetAdresse", "CarnetAdresse")
                        .WithMany("Certificats")
                        .HasForeignKey("CarnetAdresseCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.Devise", "Devise")
                        .WithMany()
                        .HasForeignKey("DeviseCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.Etat", "Etat")
                        .WithMany("Certificats")
                        .HasForeignKey("EtatCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.Pays", "PaysDestination")
                        .WithMany()
                        .HasForeignKey("PaysDestinationCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.Port", "PortCongo")
                        .WithMany()
                        .HasForeignKey("PortCongoCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.Port", "PortSortie")
                        .WithMany()
                        .HasForeignKey("PortSortieCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.RouteNationale", "Route")
                        .WithMany()
                        .HasForeignKey("RouteCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("COService.Domain.Entities.CertificateType", "Type")
                        .WithMany("Certificats")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COService.Domain.Entities.ZoneProduction", "ZoneProduction")
                        .WithMany("Certificats")
                        .HasForeignKey("ZoneProductionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Abonnement");

                    b.Navigation("Aeroport");

                    b.Navigation("BattantPavillon");

                    b.Navigation("BureauDedouanement");

                    b.Navigation("CarnetAdresse");

                    b.Navigation("Devise");

                    b.Navigation("Etat");

                    b.Navigation("Module");

                    b.Navigation("PaysDestination");

                    b.Navigation("PortCongo");

                    b.Navigation("PortSortie");

                    b.Navigation("Route");

                    b.Navigation("Type");

                    b.Navigation("ZoneProduction");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateValidation", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "CertificatOrigine")
                        .WithMany("CertificateValidations")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificatOrigine");
                });

            modelBuilder.Entity("COService.Domain.Entities.ChapitreTarifaire", b =>
                {
                    b.HasOne("COService.Domain.Entities.SectionTarifaire", "SectionTarifaire")
                        .WithMany("ChapitresTariffaires")
                        .HasForeignKey("SectionTarifaireId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SectionTarifaire");
                });

            modelBuilder.Entity("COService.Domain.Entities.Commentaire", b =>
                {
                    b.HasOne("COService.Domain.Entities.CertificatOrigine", "CertificatOrigine")
                        .WithMany("Commentaires")
                        .HasForeignKey("CertificateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CertificatOrigine");
                });

            modelBuilder.Entity("COService.Domain.Entities.DivisionTarifaire", b =>
                {
                    b.HasOne("COService.Domain.Entities.ChapitreTarifaire", "Chapitre")
                        .WithMany("DivisionsTariffaires")
                        .HasForeignKey("ChapitreId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Chapitre");
                });

            modelBuilder.Entity("COService.Domain.Entities.Incoterm", b =>
                {
                    b.HasOne("COService.Domain.Entities.Module", "Module")
                        .WithMany("Incoterms")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Module");
                });

            modelBuilder.Entity("COService.Domain.Entities.Port", b =>
                {
                    b.HasOne("COService.Domain.Entities.Pays", "Pays")
                        .WithMany("Ports")
                        .HasForeignKey("PaysId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Pays");
                });

            modelBuilder.Entity("COService.Domain.Entities.PositionTarifaire", b =>
                {
                    b.HasOne("COService.Domain.Entities.CategorieTarifaire", "Categorie")
                        .WithMany("PositionsTariffaires")
                        .HasForeignKey("CategorieCodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("COService.Domain.Entities.TauxDeChange", b =>
                {
                    b.HasOne("COService.Domain.Entities.Devise", "Devise")
                        .WithMany("TauxDeChanges")
                        .HasForeignKey("DeviseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Devise");
                });

            modelBuilder.Entity("COService.Domain.Entities.Troncon", b =>
                {
                    b.HasOne("COService.Domain.Entities.Corridor", "Corridor")
                        .WithMany("Troncons")
                        .HasForeignKey("CorridorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("COService.Domain.Entities.RouteNationale", "Route")
                        .WithMany("Troncons")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Corridor");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("COService.Domain.Entities.Abonnement", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("COService.Domain.Entities.BattantPavillon", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("COService.Domain.Entities.CarnetAdresse", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("COService.Domain.Entities.CategorieTarifaire", b =>
                {
                    b.Navigation("PositionsTariffaires");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificatOrigine", b =>
                {
                    b.Navigation("CertificatLignes");

                    b.Navigation("CertificateValidations");

                    b.Navigation("Commentaires");
                });

            modelBuilder.Entity("COService.Domain.Entities.CertificateType", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("COService.Domain.Entities.ChapitreTarifaire", b =>
                {
                    b.Navigation("DivisionsTariffaires");
                });

            modelBuilder.Entity("COService.Domain.Entities.Corridor", b =>
                {
                    b.Navigation("Troncons");
                });

            modelBuilder.Entity("COService.Domain.Entities.Devise", b =>
                {
                    b.Navigation("TauxDeChanges");
                });

            modelBuilder.Entity("COService.Domain.Entities.DivisionTarifaire", b =>
                {
                    b.Navigation("CategoriesTariffaires");
                });

            modelBuilder.Entity("COService.Domain.Entities.Etat", b =>
                {
                    b.Navigation("Certificats");
                });

            modelBuilder.Entity("COService.Domain.Entities.Module", b =>
                {
                    b.Navigation("Incoterms");
                });

            modelBuilder.Entity("COService.Domain.Entities.Pays", b =>
                {
                    b.Navigation("Aeroports");

                    b.Navigation("Ports");
                });

            modelBuilder.Entity("COService.Domain.Entities.RouteNationale", b =>
                {
                    b.Navigation("Troncons");
                });

            modelBuilder.Entity("COService.Domain.Entities.SectionTarifaire", b =>
                {
                    b.Navigation("ChapitresTariffaires");
                });

            modelBuilder.Entity("COService.Domain.Entities.ZoneProduction", b =>
                {
                    b.Navigation("Certificats");
                });
#pragma warning restore 612, 618
        }
    }
}
